blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/community
    about: Please ask general questions here.

issue_templates:
  - name: "Bug Report"
    description: "Report a bug in the API"
    title: "[Bug]: "
    labels: ["bug","needs-triage"]
    body: .github/ISSUE_TEMPLATE/bug_report.md
  - name: "Feature Request"
    description: "Suggest a new feature"
    title: "[Feature]: "
    labels: ["enhancement"]
    body: .github/ISSUE_TEMPLATE/feature_request.md
  - name: "Task"
    description: "Development task"
    title: "[Task]: "
    labels: ["task"]
    body: .github/ISSUE_TEMPLATE/task.md
---