blank_issues_enabled: false

contact_links:
  - name: 📚 API Documentation
    url: https://api-to-do-dotnet-staging.onrender.com/swagger
    about: View the API documentation and test endpoints
  - name: 💬 GitHub Discussions
    url: https://github.com/viniciusmaciel/api-to-do-dotnet/discussions
    about: Ask questions and discuss features with the community
